# Generated by Django 4.1.7 on 2023-03-08 20:03

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='default/44884218_345707102882519_2446069589734326272_n.jpg', upload_to=apps.accounts.models.get_profile_image_pathname),
        ),
    ]
